
fun_app_args.erl:12:19: Fun application with arguments ('b',[]) will fail since the function has type 'c' | fun(('a',[]) -> any()), which differs in the 1st argument
fun_app_args.erl:12:5: The created fun has no local return
