
try2.erl:12:1: Function run/2 has no local return
try2.erl:33:1: Function run3/2 has no local return
