# ERL-1201 - Unsafe variable

## Example

```erlang
%% foo.erl
-module(foo).
-export([t/1]).
t(X) ->
    case X of
        true ->
            Y = 2;
        _ ->
            ok
    end,
    Y.
```

```
$ erlc foo.erl
foo.erl:10:5: variable 'Y' unsafe in 'case' (line 4, column 5)
%   10|     Y.
%     |     ^
% help: call `erlc -explain ERL-1201` to see a detailed explanation
```

## Explanation

This error is generated by the Erlang linter when it sees an unsafe variable
usage. If a variable is bound in a branch of an `if`, `case`, or `receive`,
but it is not bound in all branches, using it outside the branch is unsafe.
Variables bound in different parts of the `try` construct have different
scoping rules, yet they are always unsafe outside of the whole construct.

To fix this error, assign a value to the variable in all branches. It is also
possible to return the result outside of the construct, like the example
above can be rewritten like this:

```erlang
%% foo.erl
-module(foo).
-export([t/1]).
t(X) ->
    Y = case X of
        true ->
            2;
        _ ->
            ok
    end,
    Y.
```

To learn more about variables, please refer to the [Reference Manual](`e:system:expressions#variables`).
